import { mkdirSync, renameSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

export const FEED_PROXY_CONFIG_SUBDIR = "conf";
export const FEED_PROXY_CONFIG_FILENAME = "default.conf";
export const FEED_PROXY_VARS_FILENAME = "feed-proxy-vars.json";

/**
 * Pure-data render of the Transitous-style feed-proxy nginx config.
 *
 * Both the operator-facing CLI (`packages/cli/src/lib/motis-feed-proxy.ts`)
 * and the data-manager pipeline's `gen-full-config` stage call into the
 * helpers here so the two callers stay in lockstep. The render produces:
 *
 * 1. A primary `server { ... }` block exposing each feed at
 *    `/feed/<key>` with per-entry cache/auth wiring.
 * 2. Optional per-GBFS `server { ... }` blocks for entries flagged
 *    `gbfs: true` so MOTIS can hit a stable upstream URL like
 *    `https://feed-proxy.example/gbfs/<name>/`. Enabled by default; set
 *    `includeGbfsServers: false` to render the primary block only.
 */

export interface FeedProxyEntry {
  url: string;
  headers?: Record<string, string>;
  gbfs?: boolean;
}

export type FeedProxyVars = Record<string, FeedProxyEntry>;

export interface FeedProxyBuildInput {
  /** Parsed contents of `feed-proxy-vars.json`. */
  varsJson: unknown;
  /** Absolute path where the rendered `.conf` should be written. */
  outputPath: string;
  /**
   * When true (default), also emit per-GBFS `server { }` blocks for entries
   * with `gbfs: true`. The primary `server { }` block is always emitted.
   */
  includeGbfsServers?: boolean;
  /**
   * Override the leading `# Generated by ...` comment. Defaults to the
   * data-manager wording for back-compat with existing pipeline output.
   */
  headerComment?: string;
}

export interface FeedProxyRenderOptions {
  includeGbfsServers?: boolean;
  headerComment?: string;
  /**
   * nginx `resolver` value emitted in the http context. The per-GBFS server
   * blocks use `proxy_pass $feed_upstream` (a variable), which nginx resolves at
   * REQUEST time and therefore REQUIRES a `resolver` — without it every GBFS
   * fetch fails with `502 no resolver defined to resolve <host>`. Defaults to
   * Docker's embedded DNS. Pass an empty string to omit it (e.g. for a host
   * that already sets one at the http level).
   */
  resolver?: string;
}

/** Docker's embedded DNS on user-defined networks; correct for the compose stack. */
const DEFAULT_RESOLVER = "127.0.0.11 ipv6=off valid=30s";

export interface FeedProxyBuildResult {
  /** Whether the file was actually written. Always true on success — kept as a
   * field so future callers can short-circuit on no-op writes. */
  wrote: boolean;
  /** Number of feed entries rendered into the nginx config. */
  entries: number;
}

const DEFAULT_HEADER_COMMENT =
  "# Generated by OpenMapX data-manager from Transitous feed-proxy vars";

function escapeNginxQuoted(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$");
}

function sortedEntries(vars: FeedProxyVars): Array<[string, FeedProxyEntry]> {
  return Object.entries(vars).sort(([a], [b]) => a.localeCompare(b));
}

function renderHeaderDirectives(headers: Record<string, string> | undefined): string[] {
  if (!headers) return [];
  return Object.entries(headers)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(
      ([key, value]) =>
        `      proxy_set_header "${escapeNginxQuoted(key)}" "${escapeNginxQuoted(value)}";`,
    );
}

function requireHttpUrl(url: string): URL {
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch (error) {
    throw new Error(`Invalid feed-proxy source URL "${url}": ${(error as Error).message}`);
  }
  if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
    throw new Error(`Unsupported feed-proxy URL protocol for "${url}" (expected http/https)`);
  }
  return parsed;
}

/**
 * Normalize a parsed feed-proxy vars JSON blob into the strict
 * {@link FeedProxyVars} shape: drops entries with missing/non-string URLs and
 * drops any entry that has an invalid header (empty key, empty value, or
 * non-string value). Returns `{}` if the input isn't a plain object.
 */
export function normalizeFeedProxyVars(raw: unknown): FeedProxyVars {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return {};

  const normalized: FeedProxyVars = {};
  for (const [key, value] of Object.entries(raw as Record<string, unknown>)) {
    if (!value || typeof value !== "object" || Array.isArray(value)) continue;
    const rawUrl = (value as { url?: unknown }).url;
    if (typeof rawUrl !== "string" || rawUrl.trim().length === 0) continue;
    const rawHeaders = (value as { headers?: unknown }).headers;
    const headers: Record<string, string> = {};
    let hasInvalidHeader = false;
    if (rawHeaders && typeof rawHeaders === "object" && !Array.isArray(rawHeaders)) {
      for (const [hKey, hValue] of Object.entries(rawHeaders as Record<string, unknown>)) {
        const headerName = hKey.trim();
        if (headerName.length === 0 || typeof hValue !== "string") {
          hasInvalidHeader = true;
          continue;
        }
        const trimmedValue = hValue.trim();
        if (trimmedValue.length === 0) {
          hasInvalidHeader = true;
          continue;
        }
        headers[hKey] = trimmedValue;
      }
    }
    if (hasInvalidHeader) continue;

    normalized[key] = {
      url: rawUrl.trim(),
      ...(Object.keys(headers).length > 0 ? { headers } : {}),
      gbfs: (value as { gbfs?: unknown }).gbfs === true,
    };
  }

  return normalized;
}

/** Atomically persist the normalized vars artifact shared by CLI, daemon and admin. */
export function writeFeedProxyVarsFile(outputPath: string, raw: unknown): FeedProxyVars {
  const normalized = normalizeFeedProxyVars(raw);
  const sorted = Object.fromEntries(sortedEntries(normalized));
  mkdirSync(dirname(outputPath), { recursive: true });
  const temporaryPath = `${outputPath}.tmp-${process.pid}`;
  writeFileSync(temporaryPath, `${JSON.stringify(sorted, null, 2)}\n`, "utf-8");
  renameSync(temporaryPath, outputPath);
  return sorted;
}

function renderPrimaryServer(entries: Array<[string, FeedProxyEntry]>): string[] {
  const out: string[] = [
    "server {",
    "  listen 80;",
    "  server_name _;",
    "",
    "  proxy_ssl_server_name on;",
    "  proxy_pass_header Server;",
    '  proxy_set_header User-Agent "openmapx/transitous-feed-proxy";',
    "  add_header X-Cache $upstream_cache_status;",
    "  add_header Link '<https://transitous.org/sources/>; rel=\"license\"';",
    "",
    "  proxy_cache feed-proxy;",
    '  proxy_cache_key "$request_uri";',
    "  proxy_buffering on;",
    "  proxy_ignore_headers Set-Cookie;",
    "  proxy_ignore_headers X-Accel-Expires;",
    "  proxy_ignore_headers Expires;",
    "  proxy_ignore_headers Cache-Control;",
    "  proxy_http_version 1.1;",
    "  proxy_intercept_errors on;",
    "  error_page 301 302 307 308 = @handle_redirects;",
    "  proxy_cache_valid 200 40s;",
    "  proxy_cache_valid 400 401 403 404 200s;",
    "  proxy_ignore_client_abort on;",
    "  proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504 http_429;",
    "",
    "  limit_req zone=feed-proxy-quota burst=10000 nodelay;",
    "",
    "  location = /healthz {",
    "    add_header Content-Type text/plain;",
    "    return 200 'ok';",
    "  }",
    "",
  ];

  for (const [key, entry] of entries) {
    const parsed = requireHttpUrl(entry.url);
    out.push(`  location "/feed/${encodeURIComponent(key)}" {`);
    out.push(`    set $feed_upstream "${escapeNginxQuoted(entry.url)}";`);
    out.push(`    set $original_host "${escapeNginxQuoted(parsed.hostname)}";`);
    out.push("    proxy_pass $feed_upstream;");
    for (const header of renderHeaderDirectives(entry.headers)) out.push(header);
    out.push("  }", "");
  }

  out.push(
    "  location @handle_redirects {",
    '    set $original_uri "$request_uri";',
    '    set $orig_loc "$upstream_http_location";',
    "",
    "    proxy_cache feed-proxy;",
    '    proxy_cache_key "$original_uri";',
    "    proxy_cache_valid 200 40s;",
    "    proxy_cache_valid 400 401 403 404 200s;",
    "",
    '    if ($orig_loc ~* "://") {',
    "      proxy_pass $orig_loc;",
    "      break;",
    "    }",
    "",
    '    if ($orig_loc !~* "://") {',
    "      proxy_pass $scheme://$original_host$orig_loc;",
    "      break;",
    "    }",
    "  }",
    "}",
  );

  return out;
}

/**
 * Per-GBFS server blocks for entries flagged `gbfs: true`. Each one gets its
 * own server { ... } block so MOTIS can hit a stable per-GBFS upstream URL
 * (e.g. https://feed-proxy.example/gbfs/<name>/).
 */
function renderGbfsServers(entries: Array<[string, FeedProxyEntry]>): string[] {
  const out: string[] = [];
  for (const [, entry] of entries) {
    if (!entry.gbfs) continue;
    const parsedUrl = requireHttpUrl(entry.url);
    const upstream = `${parsedUrl.protocol}//${parsedUrl.host}`;
    out.push(
      "",
      "server {",
      "  listen 80;",
      `  server_name "${escapeNginxQuoted(parsedUrl.hostname)}";`,
      "",
      "  proxy_ssl_server_name on;",
      "  proxy_pass_header Server;",
      '  proxy_set_header User-Agent "openmapx/transitous-feed-proxy";',
      "  add_header X-Cache $upstream_cache_status;",
      "  add_header Link '<https://transitous.org/sources/>; rel=\"license\"';",
      "",
      "  proxy_cache feed-proxy;",
      "  proxy_buffering on;",
      "  proxy_ignore_headers Set-Cookie;",
      "  proxy_ignore_headers X-Accel-Expires;",
      "  proxy_ignore_headers Expires;",
      "  proxy_ignore_headers Cache-Control;",
      "  proxy_http_version 1.1;",
      "  proxy_cache_valid 200 80s;",
      "  proxy_cache_valid 400 401 403 404 200s;",
      "  proxy_ignore_client_abort on;",
      "  proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504 http_429;",
      "",
      "  limit_req zone=feed-proxy-quota burst=10000 nodelay;",
      "",
      "  location / {",
      `    set $feed_upstream "${escapeNginxQuoted(upstream)}";`,
      "    proxy_pass $feed_upstream;",
    );
    for (const header of renderHeaderDirectives(entry.headers)) out.push(header);
    out.push("  }", "}");
  }
  return out;
}

export function renderFeedProxyNginxConfig(
  vars: FeedProxyVars,
  options: FeedProxyRenderOptions = {},
): string {
  const includeGbfsServers = options.includeGbfsServers ?? true;
  const headerComment = options.headerComment ?? DEFAULT_HEADER_COMMENT;
  const resolver = options.resolver ?? DEFAULT_RESOLVER;
  const entries = sortedEntries(vars);
  const lines = [
    headerComment,
    "proxy_cache_path /var/cache/nginx/feed-proxy max_size=10g keys_zone=feed-proxy:10m inactive=1h;",
    "limit_req_zone $binary_remote_addr zone=feed-proxy-quota:10m rate=10000r/m;",
    "limit_req_status 429;",
    // Required for the per-GBFS `proxy_pass $feed_upstream` blocks to resolve
    // upstream hostnames at request time (else 502 "no resolver defined").
    ...(resolver.trim() ? [`resolver ${resolver.trim()};`] : []),
    "",
    ...renderPrimaryServer(entries),
  ];
  if (includeGbfsServers) {
    lines.push(...renderGbfsServers(entries));
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

/**
 * Render a feed-proxy nginx config from a parsed JSON vars object and write
 * the result to disk. Pure helper — does NOT signal nginx to reload (that's
 * pipeline orchestration handled by the caller).
 *
 * Throws if any entry's `url` fails the http/https-only protocol check; this
 * surfaces malformed upstream catalogs (e.g. an `ftp://` feed) loudly instead
 * of silently dropping the entry.
 */
export async function buildFeedProxyConfig(
  input: FeedProxyBuildInput,
): Promise<FeedProxyBuildResult> {
  const vars = normalizeFeedProxyVars(input.varsJson);
  const rendered = renderFeedProxyNginxConfig(vars, {
    includeGbfsServers: input.includeGbfsServers,
    headerComment: input.headerComment,
  });
  mkdirSync(dirname(input.outputPath), { recursive: true });
  writeFileSync(input.outputPath, rendered, "utf-8");
  return { wrote: true, entries: Object.keys(vars).length };
}
