/** Centralised list of API endpoint paths. */
export const API_ENDPOINTS = {
  geocode: "/api/integrations/geocoding/geocode",
  geocodeReverse: "/api/integrations/geocoding/geocode/reverse",
  geocodeCountry: "/api/integrations/geocoding/geocode/country",
  autocomplete: "/api/integrations/geocoding/autocomplete",
  directions: "/api/integrations/routing/directions",
  directionsOptimize: "/api/integrations/routing/directions/optimize",
  routingMatch: "/api/integrations/routing/match",
  flights: "/api/integrations/flights", // used as `${base}/${provider}/open`
  flightProviders: "/api/integrations/flights/providers",
  airportNearest: "/api/integrations/knowledge-ourairports/nearest",
  foodDelivery: "/api/integrations/food-delivery", // used as `${base}/${provider}/open`
  foodDeliveryProviders: "/api/integrations/food-delivery/providers",
  restaurantMenu: "/api/integrations/restaurants/menu",
  hotels: "/api/integrations/hotels", // used as `${base}/${provider}/open`
  hotelProviders: "/api/integrations/hotels/providers",
  hotelOfficial: "/api/integrations/hotels/official",
  hotelOffers: "/api/integrations/hotels/offers",
  hotelConfig: "/api/integrations/hotels/config",
  hotelResolve: "/api/integrations/hotels/resolve",
  elevation: "/api/elevation",
  isochrone: "/api/isochrone",
  places: "/api/places",
  traffic: "/api/traffic",
  streetViewImages: "/api/integrations/street-view-mapillary/streetview/images",
  categorySearch: "/api/integrations/poi-search/search",
  textSearch: "/api/integrations/poi-search/text",
  presetSuggest: "/api/integrations/poi-search/preset-suggest",
  chipTranslations: "/api/integrations/poi-search/chip-translations",
  fuelPricesDetail: "/api/fuel-prices/detail",
  transitStops: "/api/integrations/transit/stops",
  transitStopsNearby: "/api/integrations/transit/stops/nearby",
  transitStopSearch: "/api/integrations/transit/stops/search",
  transitStopsNearPlace: "/api/integrations/transit/stops/near-place",
  transitRoutesForPlace: "/api/integrations/transit/routes/for-place",
  transitDeparturesForPlace: "/api/integrations/transit/departures/for-place",
  transitArrivalsForPlace: "/api/integrations/transit/arrivals/for-place",
  transitAlertsForPlace: "/api/integrations/transit/alerts/for-place",
  transitFacilitiesForPlace: "/api/integrations/transit/facilities/for-place",
  transitStopInfrastructure: "/api/integrations/transit/stops/:id/infrastructure",
  transitStopPlatforms: "/api/integrations/transit/stops/:id/platform-stops",
  transitStopTimetable: "/api/integrations/transit/stops/:id/timetable",
  transitDepartures: "/api/integrations/transit/stops/:id/departures",
  transitArrivals: "/api/integrations/transit/stops/:id/arrivals",
  transitFacilities: "/api/integrations/transit/stops/:id/facilities",
  transitStopAlerts: "/api/integrations/transit/stops/:id/alerts",
  transitRoutes: "/api/integrations/transit/routes",
  transitRouteStops: "/api/integrations/transit/routes/:id/stops",
  transitRouteAlerts: "/api/integrations/transit/routes/:id/alerts",
  transitRouteLive: "/api/integrations/transit/routes/:id/live",
  transitPlan: "/api/integrations/transit/plan",
  transitLegGeometry: "/api/integrations/transit/leg-geometry",
  transitAlerts: "/api/integrations/transit/alerts",
  transitVehicles: "/api/integrations/transit/vehicles",
  transitVehicleJourney: "/api/integrations/transit/vehicles/:id",
  motisStatus: "/api/motis/status",
  motisFeeds: "/api/motis/feeds",
  dataSources: "/api/integrations/data-source",
  dataSourceSearch: "/api/integrations/data-source", // used as `${base}/${sourceId}/search`
  dataSourceDetail: "/api/integrations/data-source", // used as `${base}/${sourceId}/detail/${itemId}`
  photos: "/api/integrations/photos/search",
  reviews: "/api/integrations/reviews/reviews",
  reviewAggregate: "/api/integrations/reviews/aggregate",
  reviewSubmit: "/api/integrations/reviews/submit",
  reviewImage: "/api/integrations/reviews/image",
  reviewKeypair: "/api/reviews/keypair",
  imageProxy: "/api/image-proxy",
  hikingSearch: "/api/integrations/overlay-hiking/hiking/search",
  hikingArea: "/api/integrations/overlay-hiking/hiking/area",
  hikingDetail: "/api/integrations/overlay-hiking/hiking/details",
  hikingGeometry: "/api/integrations/overlay-hiking/hiking/geometry",
  hikingShelters: "/api/integrations/overlay-hiking/hiking/shelters",
  savedLists: "/api/saved/lists",
  savedPlaces: "/api/saved/places",
  savedLabels: "/api/saved/labels",
  savedCheck: "/api/saved/check",
  capabilities: "/api/capabilities",
} as const;
