/** Centralised list of API endpoint paths. */
export const API_ENDPOINTS = {
  geocode: "/api/integrations/geocoding/geocode",
  geocodeReverse: "/api/integrations/geocoding/geocode/reverse",
  geocodeCountry: "/api/integrations/geocoding/geocode/country",
  autocomplete: "/api/integrations/geocoding/autocomplete",
  searchSuggestions: "/api/integrations/search-suggestions/search",
  directions: "/api/integrations/routing/directions",
  directionsOptimize: "/api/integrations/routing/directions/optimize",
  directionsEv: "/api/integrations/routing/directions/ev",
  routingMatch: "/api/integrations/routing/match",
  navigationAlerts: "/api/integrations/routing/navigation/alerts",
  roadConditions: "/api/integrations/road-conditions/events",
  roadConditionsFlowRoute: "/api/integrations/road-conditions/flow-along-route",
  crowdReportsSubmit: "/api/integrations/crowd-reports/reports",
  crowdReportsVote: "/api/integrations/crowd-reports/reports", // used as `${base}/${id}/${action}`
  crowdReportsEnroll: "/api/integrations/crowd-reports/enroll",
  crowdReportsTokens: "/api/integrations/crowd-reports/tokens",
  crowdReportsIssuerKeys: "/api/integrations/crowd-reports/issuer-keys",
  flights: "/api/integrations/flights", // used as `${base}/${provider}/open`
  flightProviders: "/api/integrations/flights/providers",
  rideHailing: "/api/integrations/ride-hailing", // used as `${base}/${provider}/open`
  rideProviders: "/api/integrations/ride-hailing/providers",
  rideQuotes: "/api/integrations/ride-hailing/quotes",
  airportNearest: "/api/integrations/knowledge-ourairports/nearest",
  foodDelivery: "/api/integrations/food-delivery", // used as `${base}/${provider}/open`
  foodDeliveryProviders: "/api/integrations/food-delivery/providers",
  foodDeliveryResolve: "/api/integrations/food-delivery/resolve",
  restaurantMenu: "/api/integrations/restaurants/menu",
  hotels: "/api/integrations/hotels", // used as `${base}/${provider}/open`
  hotelProviders: "/api/integrations/hotels/providers",
  hotelOfficial: "/api/integrations/hotels/official",
  hotelOffers: "/api/integrations/hotels/offers",
  hotelConfig: "/api/integrations/hotels/config",
  hotelResolve: "/api/integrations/hotels/resolve",
  elevation: "/api/elevation",
  isochrone: "/api/isochrone",
  places: "/api/places",
  neighborhoods: "/api/neighborhoods",
  traffic: "/api/traffic",
  categorySearch: "/api/integrations/poi-search/search",
  textSearch: "/api/integrations/poi-search/text",
  presetSuggest: "/api/integrations/poi-search/preset-suggest",
  chipTranslations: "/api/integrations/poi-search/chip-translations",
  poiFilter: "/api/integrations/poi-search/filter",
  brandSuggest: "/api/integrations/poi-search/brand-suggest",
  brandDetail: "/api/integrations/poi-search/brand",
  brandLogoAttribution: "/api/integrations/poi-search/brand", // used as `${base}/${qid}/logo-attribution`
  fuelPricesDetail: "/api/fuel-prices/detail",
  transitStops: "/api/integrations/transit/stops",
  transitStopsNearby: "/api/integrations/transit/stops/nearby",
  transitStopSearch: "/api/integrations/transit/stops/search",
  transitStopsNearPlace: "/api/integrations/transit/stops/near-place",
  transitRoutesForPlace: "/api/integrations/transit/routes/for-place",
  transitDeparturesForPlace: "/api/integrations/transit/departures/for-place",
  transitArrivalsForPlace: "/api/integrations/transit/arrivals/for-place",
  transitAlertsForPlace: "/api/integrations/transit/alerts/for-place",
  transitFacilitiesForPlace: "/api/integrations/transit/facilities/for-place",
  transitStopInfrastructure: "/api/integrations/transit/stops/:id/infrastructure",
  transitStopTransfers: "/api/integrations/transit/stops/:id/transfers",
  transitStopPlatforms: "/api/integrations/transit/stops/:id/platform-stops",
  transitStopTimetable: "/api/integrations/transit/stops/:id/timetable",
  transitDepartures: "/api/integrations/transit/stops/:id/departures",
  transitArrivals: "/api/integrations/transit/stops/:id/arrivals",
  transitFacilities: "/api/integrations/transit/stops/:id/facilities",
  transitStopAlerts: "/api/integrations/transit/stops/:id/alerts",
  transitRoutes: "/api/integrations/transit/routes",
  transitRouteStops: "/api/integrations/transit/routes/:id/stops",
  transitRouteAlerts: "/api/integrations/transit/routes/:id/alerts",
  transitRouteLive: "/api/integrations/transit/routes/:id/live",
  transitPlan: "/api/integrations/transit/plan",
  transitPlanRefresh: "/api/integrations/transit/plan/refresh",
  transitPlanningCapabilities: "/api/integrations/transit/planning-capabilities",
  transitReachabilityCapabilities: "/api/integrations/transit/reachability/capabilities",
  transitReachabilitySurface: "/api/integrations/transit/reachability/surface",
  transitReachabilityCheck: "/api/integrations/transit/reachability/check",
  transitLegGeometry: "/api/integrations/transit/leg-geometry",
  transitAlerts: "/api/integrations/transit/alerts",
  transitVehicles: "/api/integrations/transit/vehicles",
  transitVehicleJourney: "/api/integrations/transit/vehicles/:id",
  dataSources: "/api/integrations/data-source",
  dataSourceSearch: "/api/integrations/data-source", // used as `${base}/${sourceId}/search`
  dataSourceDetail: "/api/integrations/data-source", // used as `${base}/${sourceId}/detail/${itemId}`
  photos: "/api/integrations/photos/search",
  reviews: "/api/integrations/reviews/reviews",
  reviewAggregate: "/api/integrations/reviews/aggregate",
  reviewSubmit: "/api/integrations/reviews/submit",
  reviewImage: "/api/integrations/reviews/image",
  reviewKeypair: "/api/reviews/keypair",
  imageProxy: "/api/image-proxy",
  hikingSearch: "/api/integrations/overlay-hiking/hiking/search",
  hikingArea: "/api/integrations/overlay-hiking/hiking/area",
  hikingDetail: "/api/integrations/overlay-hiking/hiking/details",
  hikingGeometry: "/api/integrations/overlay-hiking/hiking/geometry",
  hikingShelters: "/api/integrations/overlay-hiking/hiking/shelters",
  savedLists: "/api/saved/lists",
  savedPlaces: "/api/saved/places",
  savedLabels: "/api/saved/labels",
  savedCheck: "/api/saved/check",
  vehicles: "/api/vehicles",
  parking: "/api/parking",
  // Public resolve is `${base}/${token}`; rotate is `${base}/${id}/rotate`.
  shares: "/api/shares",
  capabilities: "/api/capabilities",
  timelineConnection: "/api/timeline/connection",
  timelineConnectionTest: "/api/timeline/connection/test",
  timelineDay: "/api/timeline/day",
  nlpParse: "/api/integrations/search-nlp/parse",
  osmContributionCapabilities: "/api/osm/contributions/capabilities",
  // Base path; the element context is `${base}/${type}/${id}`.
  osmContributions: "/api/osm/contributions",
  osmContributionCategories: "/api/osm/contributions/categories",
  osmContributionPreview: "/api/osm/contributions/preview",
  osmContributionPublish: "/api/osm/contributions/publish",
  osmContributionNotes: "/api/osm/contributions/notes",
} as const;
