/** Centralised list of API endpoint paths. */
export const API_ENDPOINTS = {
  geocode: "/api/integrations/geocoding/geocode",
  geocodeReverse: "/api/integrations/geocoding/geocode/reverse",
  autocomplete: "/api/integrations/geocoding/autocomplete",
  directions: "/api/integrations/routing/directions",
  directionsOptimize: "/api/integrations/routing/directions/optimize",
  elevation: "/api/elevation",
  isochrone: "/api/isochrone",
  places: "/api/places",
  traffic: "/api/traffic",
  streetViewImages: "/api/integrations/street-view-mapillary/streetview/images",
  categorySearch: "/api/places/search",
  fuelPricesDetail: "/api/fuel-prices/detail",
  transitStops: "/api/transit/stops",
  transitStopsNearby: "/api/transit/stops/nearby",
  transitStopSearch: "/api/transit/stops/search",
  transitStopsNearPlace: "/api/transit/stops/near-place",
  transitRoutesForPlace: "/api/transit/routes/for-place",
  transitDeparturesForPlace: "/api/transit/departures/for-place",
  transitArrivalsForPlace: "/api/transit/arrivals/for-place",
  transitAlertsForPlace: "/api/transit/alerts/for-place",
  transitFacilitiesForPlace: "/api/transit/facilities/for-place",
  transitStopPlatforms: "/api/transit/stops/:id/platform-stops",
  transitStopTimetable: "/api/transit/stops/:id/timetable",
  transitDepartures: "/api/transit/stops/:id/departures",
  transitArrivals: "/api/transit/stops/:id/arrivals",
  transitFacilities: "/api/transit/stops/:id/facilities",
  transitStopAlerts: "/api/transit/stops/:id/alerts",
  transitRoutes: "/api/transit/routes",
  transitRouteStops: "/api/transit/routes/:id/stops",
  transitRouteAlerts: "/api/transit/routes/:id/alerts",
  transitRouteLive: "/api/transit/routes/:id/live",
  transitPlan: "/api/transit/plan",
  transitAlerts: "/api/transit/alerts",
  transitVehicles: "/api/transit/vehicles",
  transitVehicleJourney: "/api/transit/vehicles/:id",
  transitProviders: "/api/transit/providers",
  motisStatus: "/api/motis/status",
  motisFeeds: "/api/motis/feeds",
  dataSources: "/api/data-sources",
  dataSourceSearch: "/api/data-sources", // used as `${base}/${sourceId}/search`
  dataSourceDetail: "/api/data-sources", // used as `${base}/${sourceId}/detail/${itemId}`
  photos: "/api/integrations/photos/search",
  imageProxy: "/api/image-proxy",
  hikingSearch: "/api/integrations/overlay-hiking/hiking/search",
  hikingArea: "/api/integrations/overlay-hiking/hiking/area",
  hikingDetail: "/api/integrations/overlay-hiking/hiking/details",
  hikingGeometry: "/api/integrations/overlay-hiking/hiking/geometry",
  hikingShelters: "/api/integrations/overlay-hiking/hiking/shelters",
  savedLists: "/api/saved/lists",
  savedPlaces: "/api/saved/places",
  savedLabels: "/api/saved/labels",
  savedCheck: "/api/saved/check",
  risMapsPositions: "/api/ris-maps/positions",
  risMapsGeometry: "/api/ris-maps/geometry",
  capabilities: "/api/capabilities",
} as const;
