export {
  feedTagFromSource,
  getArrivals,
  getDepartures,
  getRoutesForStop,
  getStopById,
  getStops,
  getTrip,
  getVehicleRadar,
  motisPlaceToJourneyStop,
  normalizeStop,
  normalizeStoptime,
  planTrip,
  rawId,
  searchByName,
} from "@integrations/transit-motis/adapter";
