// Runtime (Zod) boundary schemas. Only *values* are re-exported here; the
// inferred types are published through `../types` so no name appears twice in
// the package barrel.
export {
  countCodePoints,
  OSM_MAX_CHANGES_PER_SUBMISSION,
  OSM_MAX_COMMENT_CODE_POINTS,
  OSM_MAX_EVIDENCE_DETAIL_CODE_POINTS,
  OSM_MAX_NOTE_CODE_POINTS,
  OSM_MAX_TAG_CODE_POINTS,
  OSM_MIN_COMMENT_CODE_POINTS,
  OSM_MIN_EVIDENCE_DETAIL_CODE_POINTS,
  OSM_MIN_NOTE_CODE_POINTS,
  osmAddressFieldSchema,
  osmAddressPatchSchema,
  osmAddressValueOperationSchema,
  osmCategorySearchQuerySchema,
  osmCategorySuggestionSchema,
  osmContributionCapabilitiesSchema,
  osmContributionContextSchema,
  osmContributionErrorBodySchema,
  osmContributionErrorCodeSchema,
  osmContributionPreviewRequestSchema,
  osmContributionPreviewSchema,
  osmContributionPublishRequestSchema,
  osmContributionPublishResultSchema,
  osmContributionScopeSchema,
  osmEditableFieldNameSchema,
  osmEditableFieldSchema,
  osmEditorGeometrySchema,
  osmElementRefSchema,
  osmElementTypeSchema,
  osmEvidenceSchema,
  osmFieldChangeSchema,
  osmFieldChangesSchema,
  osmFieldDisabledReasonSchema,
  osmGeometrySchema,
  osmIdempotencyKeySchema,
  osmLocaleSchema,
  osmNoteRequestSchema,
  osmNoteResultSchema,
  osmPresetIdSchema,
  osmPresetMatchStatusSchema,
  osmPreviewWarningSchema,
  osmPublicAccountSchema,
  osmScalarEditableFieldSchema,
  osmSemanticDiffSchema,
  osmTagDiffSchema,
  parseOsmElementId,
} from "./osmContribution";
