import InitColorSchemeScript from "@mui/material/InitColorSchemeScript";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import type { Metadata, Viewport } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import "mapillary-js/dist/mapillary.css";
import "maplibre-theme/icons.default.css";
import "maplibre-theme/classic.css";
import "./globals.css";
import { OfflineNotice } from "@/components/OfflineNotice";
import { FileOpenHandler } from "@/components/pwa/FileOpenHandler";
import { PersistentStorageRequest } from "@/components/pwa/PersistentStorageRequest";
import { SwUpdateNotice } from "@/components/pwa/SwUpdateNotice";
import { InstallPromptCapture } from "@/components/pwa/useInstallPrompt";
import { EnvProvider } from "@/lib/EnvProvider";
import { buildClientEnv } from "@/lib/env";
import { Providers } from "./providers";

// Singletons exposed to community integration bundles. The bundles list these
// specifiers as externals; the browser resolves them via the import map below
// to prebuilt ESM files under public/runtime/ (generated by
// scripts/build-runtime-modules.mjs). Keep in sync with that script.
const RUNTIME_IMPORTMAP = JSON.stringify({
  imports: {
    react: "/runtime/react.js",
    "react/jsx-runtime": "/runtime/react-jsx-runtime.js",
    "react/jsx-dev-runtime": "/runtime/react-jsx-dev-runtime.js",
    "@openmapx/core": "/runtime/openmapx-core.js",
    "@openmapx/integration-framework": "/runtime/openmapx-integration-framework.js",
    "@openmapx/integration-framework/react": "/runtime/openmapx-integration-framework-react.js",
  },
});

const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "OpenMapX",
  description: "Open-data maps — a Google Maps alternative",
  applicationName: "OpenMapX",
  appleWebApp: {
    capable: true,
    title: "OpenMapX",
    statusBarStyle: "black-translucent",
  },
  formatDetection: {
    telephone: false,
  },
  icons: {
    icon: [
      { url: "/icons/app/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/app/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/app/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/icons/app/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#007b8b" },
    { media: "(prefers-color-scheme: dark)", color: "#1c1c1c" },
  ],
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const locale = await getLocale();
  const messages = await getMessages();
  const clientEnv = buildClientEnv();

  return (
    <html lang={locale} className={plusJakartaSans.variable} suppressHydrationWarning>
      <head>
        <link rel="stylesheet" href="/fonts/material-icons.css" />
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: importmap content is a build-time JSON literal */}
        <script type="importmap" dangerouslySetInnerHTML={{ __html: RUNTIME_IMPORTMAP }} />
      </head>
      <body className="h-dvh overflow-hidden antialiased">
        <InitColorSchemeScript attribute="class" defaultMode="system" />
        <AppRouterCacheProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <EnvProvider config={clientEnv}>
              <Providers>
                {children}
                {/* Mounted at the root so the SW registers, the offline
                    notice surfaces on every route, and the install-prompt
                    listener attaches before `beforeinstallprompt` fires (it
                    would be missed if it lived inside the HamburgerMenu's
                    temporary Drawer subtree). Each component is a client
                    island with its own production / serviceWorker guards. */}
                <OfflineNotice />
                <SwUpdateNotice />
                <InstallPromptCapture />
                <PersistentStorageRequest />
                <FileOpenHandler />
              </Providers>
            </EnvProvider>
          </NextIntlClientProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
