// Auth tables (generated by better-auth CLI)
export {
  account,
  accountRelations,
  passkey,
  passkeyRelations,
  session,
  sessionRelations,
  twoFactor,
  twoFactorRelations,
  user,
  userRelations,
  verification,
} from "./auth-schema";

// Saved places tables
export {
  labeledPlace,
  labeledPlaceRelations,
  savedList,
  savedListRelations,
  savedPlace,
  savedPlaceRelations,
} from "./saved-schema";
