// Capability bindings — explicit (integration, capability) → service mappings

// Admin audit log
export { adminAuditLog } from "./admin-audit-schema";
// Admin jobs
export { adminJob, adminJobLog } from "./admin-job-schema";
// App logs (persisted WARN+ from ring buffer)
export { appLog } from "./app-log-schema";
// Auth tables (generated by better-auth CLI)
export {
  account,
  accountRelations,
  passkey,
  passkeyRelations,
  session,
  sessionRelations,
  twoFactor,
  twoFactorRelations,
  user,
  userRelations,
  verification,
} from "./auth-schema";
export { type CapabilityBindingRow, capabilityBinding } from "./capability-binding-schema";
// Health history
export { healthHistory } from "./health-history-schema";
// Installed community integrations
export { installedIntegration } from "./installed-integration-schema";
// Integration config
export { integrationConfig } from "./integration-config-schema";
// Integration secrets
export { integrationSecret } from "./integration-secret-schema";
// Mangrove.reviews user keypair
export { mangroveKeypair, mangroveKeypairWrap } from "./mangrove-keypair-schema";
// Saved places tables
export {
  labeledPlace,
  labeledPlaceRelations,
  savedList,
  savedListRelations,
  savedPlace,
  savedPlaceRelations,
} from "./saved-schema";
// Community service repositories
export { type ServiceRepositoryRow, serviceRepository } from "./service-repository-schema";
// System settings
export { systemSettings } from "./system-settings-schema";
