import { existsSync, readFileSync } from "node:fs";
import {
  type FeedProxyEntry,
  type FeedProxyVars,
  normalizeFeedProxyVars,
  renderFeedProxyNginxConfig as renderSharedFeedProxyNginxConfig,
} from "@openmapx/motis-feed-proxy-config";

export type TransitousFeedProxyEntry = FeedProxyEntry;
export type TransitousFeedProxyVars = FeedProxyVars;

const CLI_HEADER_COMMENT = "# Generated by OpenMapX from Transitous feed-proxy vars";

export function readFeedProxyVars(jsonPath: string): TransitousFeedProxyVars {
  if (!existsSync(jsonPath)) return {};
  const parsed = JSON.parse(readFileSync(jsonPath, "utf-8")) as unknown;
  return normalizeFeedProxyVars(parsed);
}

export function renderFeedProxyNginxConfig(vars: TransitousFeedProxyVars): string {
  return renderSharedFeedProxyNginxConfig(vars, {
    includeGbfsServers: true,
    headerComment: CLI_HEADER_COMMENT,
  });
}
