// Public barrel. Add new exports to the per-folder sub-barrels
// (src/<folder>/index.ts), not to this file. The `./navigation` and
// `./git-url` blocks stay explicit: navigation curates a subset of its
// folder and git-url is a single file whose node-only siblings live in
// `./server`.

export {
  DEFAULT_TRANSIT_ISOCHRONE_MAX_SAMPLES,
  MAX_TRANSIT_ISOCHRONE_AREA_KM2,
  TRANSIT_ISOCHRONE_METHOD,
  type TransitIsochroneRequest,
  type TransitIsochroneResult,
  type TransitIsochroneSampling,
} from "@openmapx/mobility-core/transit-isochrone";
export {
  MAX_TRANSIT_REACHABILITY_DESTINATIONS,
  MAX_TRANSIT_REACHABILITY_MINUTES,
  MAX_TRANSIT_REACHABILITY_THRESHOLDS,
  TRANSIT_WALK_PROFILE,
  type TransitExactPointCheckReason,
  type TransitExportableIsochroneReason,
  type TransitReachabilityCapabilities,
  type TransitReachabilityCheckRequest,
  type TransitReachabilityCheckResult,
  type TransitReachabilityDestination,
  type TransitReachabilityDestinationResult,
  type TransitReachabilitySeed,
  type TransitReachabilitySource,
  type TransitReachabilitySurface,
  type TransitReachabilitySurfaceRequest,
} from "@openmapx/mobility-core/transit-reachability";
export * from "./api";
export * from "./auth";
export * from "./constants";
export * from "./domains";
export * from "./feed-id";
// Git URL allowlist (shared by community service repos + community integrations).
// The `gitShallowClone*` helpers that use these live in `./server` — they import
// `node:fs` and would break the client bundle if re-exported here.
// `repoPaths`, the `services` namespace, and `spawnWithBufferedLogs` use node:fs
// / node:child_process — they live in `./server`, not this client-reachable barrel.
export {
  ALLOWED_GIT_HOSTS,
  type AllowedGitUrl,
  assertAllowedGitUrl,
  canonicalGitUrl,
  InvalidGitUrlError,
} from "./git-url";
export * from "./hooks";
export * from "./impact";
export {
  type ActiveAlert,
  type AlongRouteOptions,
  type AlongRoutePoi,
  type ApproachCamera,
  angularDifference,
  appendCountrySpans,
  approachCamera,
  type BuildGroundPackageInput,
  type BuildGroundPackageResult,
  bearingBetween,
  brakingDistanceMeters,
  buildGroundNavigationPackage,
  buildJunctionSchematic,
  CAMERA_RESTRICTED_COUNTRIES,
  type CoastOptions,
  type CoastResult,
  coastState,
  computeProgress,
  computeTransitProgress,
  countryAtMeters,
  createNavigationSessionSnapshot,
  cumulativeDistances,
  DEFAULT_CORRIDOR_PAD_METERS,
  type DeadReckonOptions,
  type DeadReckonTarget,
  detectMissedConnection,
  eta,
  evaluateFasterRoute,
  extractTimeline,
  extractTrafficSignals,
  FASTER_ROUTE_DEFAULTS,
  type FasterRouteCandidate,
  type FasterRouteEvaluation,
  type FasterRouteOptions,
  findJunctionCandidates,
  findJunctionDecisionPoints,
  flowSeverityRank,
  formatIncidentAnnouncement,
  freshNavTickState,
  type GeometryWindow,
  type GroundNavigationSettings,
  type GroundPackageError,
  groundRouteFingerprint,
  guidanceApproachMeters,
  type IncidentAlert,
  isLiveNavigationStatus,
  isNavigationSessionExpired,
  isOverSpeed,
  isReroutingTooOften,
  junctionLookupPoints,
  junctionPhotoApproachMeters,
  type ManeuverArrowSpans,
  maneuverArrowLine,
  maneuverArrowSpans,
  maneuverArrowTipBearing,
  matchCountriesByPoint,
  matchSpeedLimitsByPoint,
  mergeExitPanel,
  NAV_RECORDING_VERSION,
  NAVIGATION_SESSION_MAX_AGE_MS,
  NAVIGATION_SESSION_SCHEMA_VERSION,
  type NavigationSessionSnapshot,
  type NavRecording,
  navigationSessionFingerprint,
  navOptionsForMode,
  nextVoiceCue,
  OVER_SPEED_TOLERANCE_KMH,
  type PhotoCropWindow,
  type PhotoPathPoint,
  type PhotoProjectionOptions,
  type PhotoRoutePath,
  PROGRESS_BUCKET_METERS,
  type PreparedRouteMatcher,
  type PreparedTransitProgress,
  type ProjectEventsOptions,
  type ProjectFlowOptions,
  paddedRouteAheadBounds,
  parseLaneTags,
  parseNavigationSessionSnapshot,
  pickSpeedLimit,
  poiAlongRoute,
  positionAt,
  prepareRouteMatcher,
  prepareTransitProgress,
  processFix,
  progressBucket,
  progressBucketStartMeters,
  projectEventsToRoute,
  projectFlowToRoute,
  projectRoutePath,
  pruneRerouteTimes,
  type RecordedReroute,
  type ReplayStep,
  type RoadAlert,
  type RoadAlertType,
  type RouteCountrySpan,
  readRouteMatcherCounters,
  refKind,
  remainingWaypoints,
  replayRecording,
  resetRouteMatcherCounters,
  resolveRecommendedLanes,
  routeAheadBounds,
  routeFingerprint,
  SIGNAL_LOST_GAP_MS,
  sameJunction,
  selectActiveAlert,
  selectApproachWay,
  selectJunctionPhoto,
  selectRampWay,
  setRouteMatcherCounting,
  shouldPreviewNextStep,
  shouldReroute,
  shouldRerouteForClosure,
  shouldWarnCamera,
  signalCoordKey,
  signHeadline,
  simulatePositions,
  snapPreparedRoute,
  snapToRoute,
  stepDeadReckon,
  stepStartMeters,
  stopsUntilAlight,
  type TimelineEvent,
  type TimelineEventType,
  upcomingManeuverIndex,
  updateOffRouteScore,
  visibleToward,
  windowGeometry,
} from "./navigation";
export type { TransitProgress } from "./navigation/transitProgress";
export type {
  CameraMode,
  CueTier,
  FixInput,
  NavProgress,
  NavStatus,
  NavTickOptions,
  NavTickResult,
  NavTickState,
  ProgressResult,
  RerouteOpts,
  SnapResult,
  VoiceCue,
} from "./navigation/types";
export * from "./offline";
export * from "./panels";
export * from "./platform";
export * from "./routing";
export * from "./schemas";
export * from "./stores";
export * from "./types";
export * from "./utils";
export * from "./vehicles";
