/**
 * Regenerates `packages/ev-charge-planner/src/vehicles.generated.ts` from a
 * pinned open-ev-data release. Run with `pnpm gen-ev-vehicles`.
 *
 * The generated table is committed, so nothing downloads at runtime or during
 * `docker build`. Bump DATASET_TAG and re-run to pick up a newer release.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  type DropReason,
  dedupeVehicles,
  disambiguateLabels,
  type GeneratedVehicle,
  mapVehicle,
  type RawVehicle,
} from "./map-vehicle.ts";

const DATASET_TAG = "v1.24.0";
const DATASET_REPO = "open-ev-data/open-ev-data-dataset";
const DATASET_URL = `https://github.com/${DATASET_REPO}/releases/download/${DATASET_TAG}/open-ev-data-${DATASET_TAG}.json`;

const OUT_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "../../packages/ev-charge-planner/src/vehicles.generated.ts",
);

const DROP_REASONS: DropReason[] = ["no-battery", "no-dc", "hybrid", "no-range", "no-connectors"];

/** The release payload wraps the records in an object; the vehicle array is its only array-valued property. */
function extractRecords(payload: unknown): RawVehicle[] {
  if (!payload || typeof payload !== "object") {
    throw new Error("dataset payload is not an object");
  }
  const arrays = Object.entries(payload as Record<string, unknown>).filter(([, value]) =>
    Array.isArray(value),
  );
  if (arrays.length !== 1) {
    throw new Error(
      `expected exactly one array-valued property in the dataset payload, found ${arrays.length}`,
    );
  }
  return arrays[0][1] as RawVehicle[];
}

function renderRecord(vehicle: GeneratedVehicle): string {
  const connectors = vehicle.connectors.map((c) => JSON.stringify(c)).join(", ");
  return [
    "  {",
    `    id: ${JSON.stringify(vehicle.id)},`,
    `    label: ${JSON.stringify(vehicle.label)},`,
    `    make: ${JSON.stringify(vehicle.make)},`,
    `    batteryKwh: ${vehicle.batteryKwh},`,
    `    baseWhPerKm: ${vehicle.baseWhPerKm},`,
    `    massTonnes: ${vehicle.massTonnes},`,
    `    maxDcKw: ${vehicle.maxDcKw},`,
    `    maxAcKw: ${vehicle.maxAcKw},`,
    `    vehicleTaperSocPct: ${vehicle.vehicleTaperSocPct},`,
    `    connectors: [${connectors}],`,
    "  },",
  ].join("\n");
}

function renderModule(vehicles: GeneratedVehicle[]): string {
  return `// Generated by \`pnpm gen-ev-vehicles\` — do not hand-edit.
//
// Source: ${DATASET_REPO} ${DATASET_TAG} (https://github.com/${DATASET_REPO}),
// licensed CDLA-Permissive-2.0.
//
// Caveats, because the upstream records do not carry these figures directly:
//   - vehicleTaperSocPct is 80 for every vehicle; the dataset has no charge curves.
//   - baseWhPerKm is derived from the rated range via a per-cycle realism factor
//     (EPA is close to real-world, WLTP optimistic, CLTC/NEDC more so), not from
//     a measured consumption figure.
//   - massTonnes falls back to a body-type estimate when curb weight is missing.
//   - NACS is fanned out to tesla_ccs plus the market's CCS flavour, because
//     charger data collapses every NACS plug to "Tesla" and a NACS-only vehicle
//     would otherwise match no stations.
import type { ConnectorStandard } from "@openmapx/core";

export interface GeneratedVehicleRecord {
  id: string;
  label: string;
  make: string;
  batteryKwh: number;
  baseWhPerKm: number;
  massTonnes: number;
  maxDcKw: number;
  maxAcKw: number;
  vehicleTaperSocPct: number;
  connectors: ConnectorStandard[];
}

export const DATASET_VERSION = ${JSON.stringify(DATASET_TAG)};

export const GENERATED_VEHICLES: readonly GeneratedVehicleRecord[] = [
${vehicles.map(renderRecord).join("\n")}
];
`;
}

async function main(): Promise<void> {
  console.log(`Fetching ${DATASET_URL}`);
  const response = await fetch(DATASET_URL);
  if (!response.ok) {
    throw new Error(`dataset download failed: ${response.status} ${response.statusText}`);
  }
  const records = extractRecords(await response.json());

  const mapped: GeneratedVehicle[] = [];
  const drops = new Map<DropReason, number>();
  for (const record of records) {
    const result = mapVehicle(record);
    if ("ok" in result) {
      mapped.push(result.ok);
    } else {
      drops.set(result.drop, (drops.get(result.drop) ?? 0) + 1);
    }
  }

  const { kept, collapsed } = dedupeVehicles(mapped);
  const vehicles = disambiguateLabels(kept);
  // Make first: the picker groups by it, and MUI emits a duplicate group header
  // whenever a group's options are not contiguous in the option array.
  vehicles.sort(
    (a, b) =>
      a.make.localeCompare(b.make, "en") ||
      a.label.localeCompare(b.label, "en") ||
      a.id.localeCompare(b.id),
  );

  await mkdir(dirname(OUT_PATH), { recursive: true });
  await writeFile(OUT_PATH, renderModule(vehicles), "utf8");

  console.log(`\nDataset ${DATASET_TAG}`);
  console.log(`  total records: ${records.length}`);
  console.log(`  usable:        ${vehicles.length}`);
  console.log(`  collapsed:     ${collapsed} (identical duplicate records)`);
  console.log("  dropped:");
  for (const reason of DROP_REASONS) {
    console.log(`    ${reason.padEnd(15)} ${drops.get(reason) ?? 0}`);
  }
  console.log(`\nWrote ${OUT_PATH}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
