import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { buildFeedProxyConfig } from "../lib/build";

describe("buildFeedProxyConfig", () => {
  let workDir: string;

  beforeEach(() => {
    workDir = mkdtempSync(join(tmpdir(), "feed-proxy-build-"));
  });

  afterEach(() => {
    rmSync(workDir, { recursive: true, force: true });
  });

  it("renders a location block per feed entry", async () => {
    const outputPath = join(workDir, "nested", "feed-proxy.conf");
    const result = await buildFeedProxyConfig({
      varsJson: {
        "us-de": {
          url: "https://example.com/de.json",
          headers: { "X-Api-Key": "secret" },
        },
        "us-ny": { url: "https://example.com/ny.json" },
      },
      outputPath,
    });

    expect(result).toEqual({ wrote: true, entries: 2 });

    const written = readFileSync(outputPath, "utf-8");
    expect(written).toContain('location "/feed/us-de"');
    expect(written).toContain('location "/feed/us-ny"');
    expect(written).toContain('set $feed_upstream "https://example.com/de.json";');
    expect(written).toContain('proxy_set_header "X-Api-Key" "secret";');
    expect(written).toContain("limit_req zone=feed-proxy-quota");
    expect(written).toContain(
      "# Generated by OpenMapX data-manager from Transitous feed-proxy vars",
    );
  });

  it("writes a header-only config when there are no feeds", async () => {
    const outputPath = join(workDir, "feed-proxy.conf");
    const result = await buildFeedProxyConfig({
      varsJson: {},
      outputPath,
    });

    expect(result.entries).toBe(0);
    const written = readFileSync(outputPath, "utf-8");
    expect(written).toContain("server {");
    expect(written).toContain("location = /healthz");
    expect(written).not.toContain("/feed/");
  });

  it("rejects non-http(s) upstream URLs", async () => {
    const outputPath = join(workDir, "feed-proxy.conf");
    await expect(
      buildFeedProxyConfig({
        varsJson: { bad: { url: "ftp://example.com/feed.json" } },
        outputPath,
      }),
    ).rejects.toThrow(/Unsupported feed-proxy URL protocol/);
  });

  it("escapes backslashes, quotes, and dollar signs in URLs and headers", async () => {
    const outputPath = join(workDir, "feed-proxy.conf");
    await buildFeedProxyConfig({
      varsJson: {
        weird: {
          url: 'https://example.com/feed?token="quoted"&path=$VAR',
          headers: { 'X-"Quoted"': 'has $dollar and "quotes"' },
        },
      },
      outputPath,
    });

    const written = readFileSync(outputPath, "utf-8");
    expect(written).toContain('\\"quoted\\"');
    expect(written).toContain("\\$VAR");
    expect(written).toContain(
      'proxy_set_header "X-\\"Quoted\\"" "has \\$dollar and \\"quotes\\"";',
    );
  });

  it("skips entries whose vars JSON is malformed (non-string url, missing url, arrays)", async () => {
    const outputPath = join(workDir, "feed-proxy.conf");
    const result = await buildFeedProxyConfig({
      varsJson: {
        good: { url: "https://example.com/ok.json" },
        bad1: { url: 42 },
        bad2: { headers: { foo: "bar" } },
        bad3: ["array"],
        bad4: null,
      },
      outputPath,
    });

    expect(result.entries).toBe(1);
    const written = readFileSync(outputPath, "utf-8");
    expect(written).toContain('location "/feed/good"');
    expect(written).not.toContain("bad1");
    expect(written).not.toContain("bad2");
  });
});
