import {
  type SubjectDataRegistration,
  subjectDataRegistrationSchema,
  validateSubjectDataRegistrations,
} from "@openmapx/core/privacy";

/**
 * The explicit controller catalogue.  Keep this list hand-maintained: a table
 * name or manifest reflection is not a legal classification.  New persisted
 * subject data must add a registration and a collector/task before it can be
 * presented as complete.
 */
const registrationDefinitions: SubjectDataRegistration[] = [
  {
    id: "account-profile",
    version: 1,
    category: "account",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-account",
    locators: [{ type: "user_id", field: "user.id" }],
    purposes: ["account-management", "authentication"],
    legalBases: ["contract"],
    origin: { kind: "subject", descriptionCode: "subject-provided" },
    retention: { kind: "account-lifetime", daysAfterClosure: 30, reasonCode: "erasure-replay" },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "include", format: "json" },
    secretPolicy: { mode: "metadata", code: "account-safe-metadata" },
    rightsOfOthers: { mode: "none" },
  },
  {
    id: "auth-accounts",
    version: 1,
    category: "authentication",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-authentication",
    locators: [{ type: "user_id", field: "account.user_id" }],
    purposes: ["authentication", "security-and-abuse-prevention"],
    legalBases: ["contract", "legal-obligation"],
    origin: { kind: "processor", descriptionCode: "authentication-provider" },
    retention: { kind: "account-lifetime", daysAfterClosure: 30, reasonCode: "erasure-replay" },
    recipients: [
      { id: "openmapx-controller", roleCode: "controller", country: "DE" },
      { id: "openstreetmap", roleCode: "independent-controller" },
      { id: "mapillary", roleCode: "independent-controller", country: "US" },
    ],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "credential-material" },
    secretPolicy: { mode: "redact", code: "credential-redacted" },
    rightsOfOthers: { mode: "none" },
  },
  {
    id: "auth-sessions",
    version: 1,
    category: "authentication",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-authentication",
    locators: [{ type: "user_id", field: "session.user_id" }],
    purposes: ["authentication", "security-and-abuse-prevention"],
    legalBases: ["contract", "legitimate-interest"],
    origin: { kind: "controller", descriptionCode: "service-generated" },
    retention: {
      kind: "fixed-days",
      days: 30,
      daysAfterClosure: 30,
      reasonCode: "security-retention",
    },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "security-metadata" },
    secretPolicy: { mode: "redact", code: "session-token-redacted" },
    rightsOfOthers: { mode: "none" },
  },
  {
    id: "auth-verifications",
    version: 1,
    category: "authentication",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-authentication",
    locators: [
      { type: "exact_identifier", field: "verification.identifier", format: "email-or-purpose" },
    ],
    purposes: ["authentication", "account-management"],
    legalBases: ["contract"],
    origin: { kind: "controller", descriptionCode: "service-generated" },
    retention: {
      kind: "ephemeral",
      hours: 48,
      daysAfterClosure: 0,
      reasonCode: "challenge-expiry",
    },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "challenge-material" },
    secretPolicy: { mode: "redact", code: "challenge-redacted" },
    rightsOfOthers: { mode: "none" },
  },
  {
    id: "auth-passkeys",
    version: 1,
    category: "authentication",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-authentication",
    locators: [{ type: "user_id", field: "passkey.user_id" }],
    purposes: ["authentication", "security-and-abuse-prevention"],
    legalBases: ["contract"],
    origin: { kind: "subject", descriptionCode: "passkey-registration" },
    retention: { kind: "account-lifetime", daysAfterClosure: 30, reasonCode: "erasure-replay" },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "authentication-key-metadata" },
    secretPolicy: { mode: "metadata", code: "passkey-public-metadata" },
    rightsOfOthers: { mode: "none" },
  },
  {
    id: "auth-two-factor",
    version: 1,
    category: "authentication",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-authentication",
    locators: [{ type: "user_id", field: "two_factor.user_id" }],
    purposes: ["authentication", "security-and-abuse-prevention"],
    legalBases: ["contract"],
    origin: { kind: "subject", descriptionCode: "security-setting" },
    retention: { kind: "account-lifetime", daysAfterClosure: 30, reasonCode: "erasure-replay" },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "authentication-secret" },
    secretPolicy: { mode: "metadata", code: "two-factor-safe-metadata" },
    rightsOfOthers: { mode: "none" },
  },
  {
    id: "auth-oauth-resources",
    version: 1,
    category: "authentication",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-authentication",
    locators: [{ type: "user_id", field: "oauth-client.user_id" }],
    purposes: ["authentication", "service-provisioning"],
    legalBases: ["contract"],
    origin: { kind: "subject", descriptionCode: "oauth-registration" },
    retention: { kind: "account-lifetime", daysAfterClosure: 30, reasonCode: "erasure-replay" },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "authorization-secret" },
    secretPolicy: { mode: "redact", code: "oauth-secret-redacted" },
    rightsOfOthers: { mode: "none" },
  },
  {
    id: "saved-lists",
    version: 1,
    category: "saved-content",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-content",
    locators: [{ type: "user_id", field: "saved_list.user_id" }],
    purposes: ["saved-content", "personalization"],
    legalBases: ["contract"],
    origin: { kind: "subject", descriptionCode: "subject-created" },
    retention: { kind: "account-lifetime", daysAfterClosure: 0, reasonCode: "account-content" },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "include", format: "json" },
    secretPolicy: { mode: "metadata", code: "saved-content" },
    rightsOfOthers: { mode: "redact", code: "shared-content-review" },
  },
  {
    id: "saved-places",
    version: 1,
    category: "saved-content",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-content",
    locators: [{ type: "user_id", field: "saved_list.user_id" }],
    purposes: ["saved-content", "navigation"],
    legalBases: ["contract"],
    origin: { kind: "subject", descriptionCode: "subject-created" },
    retention: { kind: "account-lifetime", daysAfterClosure: 0, reasonCode: "account-content" },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "include", format: "geojson" },
    secretPolicy: { mode: "metadata", code: "saved-content" },
    rightsOfOthers: { mode: "redact", code: "shared-content-review" },
  },
  {
    id: "labeled-places",
    version: 1,
    category: "saved-content",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-content",
    locators: [{ type: "user_id", field: "labeled_place.user_id" }],
    purposes: ["saved-content", "personalization"],
    legalBases: ["contract"],
    origin: { kind: "subject", descriptionCode: "subject-created" },
    retention: { kind: "account-lifetime", daysAfterClosure: 0, reasonCode: "account-content" },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "include", format: "geojson" },
    secretPolicy: { mode: "metadata", code: "saved-content" },
    rightsOfOthers: { mode: "redact", code: "shared-content-review" },
  },
  {
    id: "personal-vehicles",
    version: 1,
    category: "vehicles",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-vehicles",
    locators: [{ type: "user_id", field: "personal_vehicle.user_id" }],
    purposes: ["personalization", "navigation"],
    legalBases: ["contract"],
    origin: { kind: "subject", descriptionCode: "subject-created" },
    retention: { kind: "account-lifetime", daysAfterClosure: 0, reasonCode: "account-content" },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "include", format: "json" },
    secretPolicy: { mode: "metadata", code: "vehicle-safe-metadata" },
    rightsOfOthers: { mode: "none" },
  },
  {
    id: "parked-locations",
    version: 1,
    category: "vehicles",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-vehicles",
    locators: [{ type: "user_id", field: "parked_location.user_id" }],
    purposes: ["navigation", "personalization"],
    legalBases: ["contract"],
    origin: { kind: "subject", descriptionCode: "subject-created" },
    retention: {
      kind: "ephemeral",
      hours: 8_760,
      daysAfterClosure: 0,
      reasonCode: "current-state",
    },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "include", format: "geojson" },
    secretPolicy: { mode: "metadata", code: "location-safe-metadata" },
    rightsOfOthers: { mode: "redact", code: "shared-location-review" },
  },
  {
    id: "share-links",
    version: 1,
    category: "sharing",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-sharing",
    locators: [{ type: "user_id", field: "share_link.user_id" }],
    purposes: ["saved-content", "publication"],
    legalBases: ["contract", "consent"],
    origin: { kind: "subject", descriptionCode: "subject-published" },
    retention: { kind: "account-lifetime", daysAfterClosure: 0, reasonCode: "revocation" },
    recipients: [
      { id: "openmapx-controller", roleCode: "controller", country: "DE" },
      { id: "public-recipient", roleCode: "public-recipient" },
    ],
    article15: "include",
    portability: { decision: "include", format: "json" },
    secretPolicy: { mode: "redact", code: "share-token-redacted" },
    rightsOfOthers: { mode: "operator_review", code: "shared-content-review" },
  },
  {
    id: "timeline-connections",
    version: 1,
    category: "timeline",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-timeline",
    locators: [{ type: "user_id", field: "personal_timeline_connection.user_id" }],
    purposes: ["timeline-processing", "service-provisioning"],
    legalBases: ["contract"],
    origin: { kind: "subject", descriptionCode: "subject-connected" },
    retention: {
      kind: "account-lifetime",
      daysAfterClosure: 0,
      reasonCode: "connection-revocation",
    },
    recipients: [
      { id: "openmapx-controller", roleCode: "controller", country: "DE" },
      { id: "dawarich-managed", roleCode: "processor", country: "DE" },
    ],
    article15: "include",
    portability: { decision: "include", format: "json" },
    secretPolicy: { mode: "redact", code: "timeline-credential-redacted" },
    rightsOfOthers: { mode: "none" },
  },
  {
    id: "mangrove-keypairs",
    version: 1,
    category: "publication-keys",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-mangrove",
    locators: [{ type: "user_id", field: "mangrove_keypair.user_id" }],
    purposes: ["publication", "security-and-abuse-prevention"],
    legalBases: ["contract"],
    origin: { kind: "subject", descriptionCode: "subject-key" },
    retention: { kind: "account-lifetime", daysAfterClosure: 0, reasonCode: "key-revocation" },
    recipients: [
      { id: "openmapx-controller", roleCode: "controller", country: "DE" },
      { id: "mangrove-reviews", roleCode: "independent-controller" },
    ],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "private-key-material" },
    secretPolicy: { mode: "metadata", code: "public-key-only" },
    rightsOfOthers: { mode: "none" },
  },
  {
    id: "mobile-auth-handoffs",
    version: 1,
    category: "authentication",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-authentication",
    locators: [{ type: "user_id", field: "mobile_auth_handoff.user_id" }],
    purposes: ["authentication"],
    legalBases: ["contract"],
    origin: { kind: "controller", descriptionCode: "service-generated" },
    retention: { kind: "ephemeral", hours: 2, daysAfterClosure: 0, reasonCode: "handoff-expiry" },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "authentication-material" },
    secretPolicy: { mode: "redact", code: "handoff-secret-redacted" },
    rightsOfOthers: { mode: "none" },
  },
  {
    id: "admin-audit-attribution",
    version: 1,
    category: "administrative-accountability",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-administration",
    locators: [
      { type: "actor_id", field: "admin_audit_log.actor_id" },
      { type: "target_id", field: "admin_audit_log.target_id" },
    ],
    purposes: ["legal-accountability", "security-and-abuse-prevention"],
    legalBases: ["legal-obligation", "legitimate-interest"],
    origin: { kind: "controller", descriptionCode: "administrative-record" },
    retention: {
      kind: "fixed-days",
      days: 3650,
      daysAfterClosure: 3650,
      reasonCode: "accountability",
    },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "legal-accountability" },
    secretPolicy: { mode: "metadata", code: "audit-safe-projection" },
    rightsOfOthers: { mode: "operator_review", code: "rights-of-others" },
  },
  {
    id: "admin-jobs-attribution",
    version: 1,
    category: "administrative-accountability",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-administration",
    locators: [{ type: "creator_id", field: "admin_job.created_by" }],
    purposes: ["legal-accountability", "support-and-operations"],
    legalBases: ["legal-obligation", "legitimate-interest"],
    origin: { kind: "controller", descriptionCode: "administrative-record" },
    retention: {
      kind: "fixed-days",
      days: 3650,
      daysAfterClosure: 3650,
      reasonCode: "accountability",
    },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "legal-accountability" },
    secretPolicy: { mode: "operator_review", code: "job-payload-review" },
    rightsOfOthers: { mode: "operator_review", code: "rights-of-others" },
  },
  {
    id: "installed-component-attribution",
    version: 1,
    category: "administrative-accountability",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-administration",
    locators: [
      { type: "creator_id", field: "installed_extension.installed_by" },
      { type: "creator_id", field: "installed_integration.installed_by" },
    ],
    purposes: ["service-provisioning", "legal-accountability"],
    legalBases: ["contract", "legal-obligation"],
    origin: { kind: "controller", descriptionCode: "administrative-record" },
    retention: {
      kind: "fixed-days",
      days: 3650,
      daysAfterClosure: 3650,
      reasonCode: "accountability",
    },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "administrative-record" },
    secretPolicy: { mode: "metadata", code: "attribution-safe-metadata" },
    rightsOfOthers: { mode: "none" },
  },
  {
    id: "secret-update-attribution",
    version: 1,
    category: "administrative-accountability",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-administration",
    locators: [
      { type: "updater_id", field: "integration_secret.updated_by" },
      { type: "updater_id", field: "service_secret.updated_by" },
    ],
    purposes: ["service-provisioning", "security-and-abuse-prevention"],
    legalBases: ["contract", "legitimate-interest"],
    origin: { kind: "controller", descriptionCode: "administrative-record" },
    retention: { kind: "account-lifetime", daysAfterClosure: 30, reasonCode: "erasure-replay" },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "operator-credential" },
    secretPolicy: { mode: "redact", code: "secret-value-redacted" },
    rightsOfOthers: { mode: "none" },
  },
  {
    id: "system-setting-attribution",
    version: 1,
    category: "administrative-accountability",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-administration",
    locators: [{ type: "updater_id", field: "system_settings.updated_by" }],
    purposes: ["service-provisioning", "legal-accountability"],
    legalBases: ["contract", "legal-obligation"],
    origin: { kind: "controller", descriptionCode: "administrative-record" },
    retention: {
      kind: "fixed-days",
      days: 3650,
      daysAfterClosure: 3650,
      reasonCode: "accountability",
    },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "operator-configuration" },
    secretPolicy: { mode: "redact", code: "setting-value-redacted" },
    rightsOfOthers: { mode: "operator_review", code: "rights-of-others" },
  },
  {
    id: "data-manager-trigger-attribution",
    version: 1,
    category: "administrative-accountability",
    source: "openmapx-db",
    strategy: "operator_task",
    locators: [{ type: "triggered_by", field: "data_manager.jobs.triggered_by" }],
    purposes: ["support-and-operations", "legal-accountability"],
    legalBases: ["legitimate-interest", "legal-obligation"],
    origin: { kind: "controller", descriptionCode: "operator-task" },
    retention: {
      kind: "fixed-days",
      days: 3650,
      daysAfterClosure: 3650,
      reasonCode: "accountability",
    },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "operational-record" },
    secretPolicy: { mode: "operator_review", code: "data-manager-review" },
    rightsOfOthers: { mode: "operator_review", code: "rights-of-others" },
  },
  {
    id: "offline-package-ownership",
    version: 1,
    category: "offline-data",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-offline",
    locators: [
      {
        type: "hmac_principal",
        field: "data_manager.offline_package_job_owners.principal",
        purposeCode: "offline-package",
      },
    ],
    purposes: ["navigation", "service-provisioning"],
    legalBases: ["contract"],
    origin: { kind: "subject", descriptionCode: "subject-requested" },
    retention: {
      kind: "fixed-days",
      days: 30,
      daysAfterClosure: 0,
      reasonCode: "offline-job-retention",
    },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "derived-package" },
    secretPolicy: { mode: "metadata", code: "offline-safe-metadata" },
    rightsOfOthers: { mode: "none" },
  },
  {
    id: "application-logs",
    version: 1,
    category: "operational-logs",
    source: "openmapx-db",
    strategy: "operator_task",
    locators: [{ type: "exact_identifier", field: "app_logs.metadata.subjectId", format: "uuid" }],
    purposes: ["security-and-abuse-prevention", "support-and-operations"],
    legalBases: ["legitimate-interest", "legal-obligation"],
    origin: { kind: "controller", descriptionCode: "operational-log" },
    retention: { kind: "fixed-days", days: 30, daysAfterClosure: 30, reasonCode: "log-retention" },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "operational-log" },
    secretPolicy: { mode: "operator_review", code: "structured-log-review" },
    rightsOfOthers: { mode: "operator_review", code: "rights-of-others" },
  },
  {
    id: "redis-subject-controls",
    version: 1,
    category: "operational-controls",
    source: "redis",
    strategy: "operator_task",
    locators: [{ type: "hmac_principal", field: "redis.namespace", purposeCode: "rate-limit" }],
    purposes: ["security-and-abuse-prevention"],
    legalBases: ["legitimate-interest"],
    origin: { kind: "controller", descriptionCode: "operational-control" },
    retention: { kind: "ephemeral", hours: 24, daysAfterClosure: 0, reasonCode: "control-expiry" },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "security-control" },
    secretPolicy: { mode: "metadata", code: "control-safe-metadata" },
    rightsOfOthers: { mode: "none" },
  },
  {
    id: "managed-dawarich",
    version: 1,
    category: "timeline",
    source: "managed-service",
    strategy: "collector",
    collectorId: "managed-dawarich-v1",
    collectorVersion: 1,
    locators: [
      { type: "managed_oidc_subject", field: "dawarich.users.uid", provider: "openid_connect" },
    ],
    purposes: ["timeline-processing", "service-provisioning"],
    legalBases: ["contract"],
    origin: { kind: "processor", descriptionCode: "managed-dawarich" },
    retention: { kind: "account-lifetime", daysAfterClosure: 0, reasonCode: "processor-retention" },
    recipients: [
      { id: "dawarich-managed", roleCode: "processor", country: "DE" },
      { id: "openmapx-controller", roleCode: "controller", country: "DE" },
    ],
    article15: "include",
    portability: { decision: "include", format: "jsonl" },
    secretPolicy: { mode: "redact", code: "dawarich-secret-redacted" },
    rightsOfOthers: { mode: "operator_review", code: "dawarich-rights-review" },
  },
  {
    id: "privacy-case-records",
    version: 1,
    category: "privacy-rights",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-privacy-case",
    locators: [{ type: "user_id", field: "data_subject_request.user_id" }],
    purposes: ["legal-accountability"],
    legalBases: ["legal-obligation"],
    origin: { kind: "controller", descriptionCode: "rights-request" },
    retention: {
      kind: "fixed-days",
      days: 1095,
      daysAfterClosure: 1095,
      reasonCode: "case-accountability",
    },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "case-accountability" },
    secretPolicy: { mode: "redact", code: "protected-case-detail" },
    rightsOfOthers: { mode: "operator_review", code: "rights-of-others" },
  },
  {
    id: "disclosure-events",
    version: 1,
    category: "disclosures",
    source: "openmapx-db",
    strategy: "collector",
    collectorId: "openmapx-disclosures",
    locators: [{ type: "user_id", field: "data_disclosure_event.user_id" }],
    purposes: ["legal-accountability", "communications", "publication"],
    legalBases: ["legal-obligation"],
    origin: { kind: "controller", descriptionCode: "disclosure-ledger" },
    retention: {
      kind: "fixed-days",
      days: 1095,
      daysAfterClosure: 1095,
      reasonCode: "recipient-accountability",
    },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "recipient-information" },
    secretPolicy: { mode: "metadata", code: "disclosure-safe-metadata" },
    rightsOfOthers: { mode: "none" },
  },
  {
    id: "backup-retained-copies",
    version: 1,
    category: "backup-copies",
    source: "operator",
    strategy: "operator_task",
    locators: [{ type: "manual", field: "backup.snapshot", instructionsCode: "backup-review" }],
    purposes: ["legal-accountability", "security-and-abuse-prevention"],
    legalBases: ["legal-obligation", "legitimate-interest"],
    origin: { kind: "operator", descriptionCode: "retained-backup" },
    retention: {
      kind: "fixed-days",
      days: 30,
      daysAfterClosure: 30,
      reasonCode: "backup-retention",
    },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "retained-copy" },
    secretPolicy: { mode: "operator_review", code: "backup-review-required" },
    rightsOfOthers: { mode: "operator_review", code: "rights-of-others" },
  },
  {
    id: "off-host-processor-sources",
    version: 1,
    category: "external-processing",
    source: "operator",
    strategy: "operator_task",
    locators: [{ type: "manual", field: "operator.source", instructionsCode: "processor-review" }],
    purposes: ["support-and-operations", "communications"],
    legalBases: ["contract", "legal-obligation"],
    origin: { kind: "operator", descriptionCode: "operator-managed-source" },
    retention: {
      kind: "fixed-days",
      days: 1095,
      daysAfterClosure: 1095,
      reasonCode: "case-accountability",
    },
    recipients: [{ id: "openmapx-controller", roleCode: "controller", country: "DE" }],
    article15: "include",
    portability: { decision: "exclude", reasonCode: "operator-source" },
    secretPolicy: { mode: "operator_review", code: "processor-review-required" },
    rightsOfOthers: { mode: "operator_review", code: "rights-of-others" },
  },
  {
    id: "global-public-data",
    version: 1,
    category: "public-data",
    source: "openmapx-db",
    strategy: "not_personal",
    locators: [],
    purposes: ["navigation"],
    legalBases: ["legitimate-interest"],
    origin: { kind: "public-source", descriptionCode: "public-data" },
    retention: { kind: "fixed-days", days: 365, daysAfterClosure: 0, reasonCode: "public-dataset" },
    recipients: [],
    article15: "not_personal",
    portability: { decision: "exclude", reasonCode: "global-public-data" },
    secretPolicy: { mode: "redact", code: "not-personal" },
    rightsOfOthers: { mode: "none" },
  },
];

const deploymentRecipientIds = new Set(["openmapx-controller", "dawarich-managed"]);
const registrations = registrationDefinitions.map((registration) => ({
  ...registration,
  recipients: registration.recipients.map((recipient) => {
    if (!deploymentRecipientIds.has(recipient.id)) return recipient;
    const { country: _deploymentSpecificCountry, ...portableRecipient } = recipient;
    return portableRecipient;
  }),
}));

const validation = validateSubjectDataRegistrations(registrations);
if (!validation.success) {
  throw new Error(`Invalid privacy catalogue: ${validation.error.message}`);
}

export const SUBJECT_DATA_CATALOGUE = Object.freeze(validation.data);
export const SUBJECT_DATA_CATALOGUE_BY_ID = new Map(
  SUBJECT_DATA_CATALOGUE.map((registration) => [registration.id, registration]),
);

export function getSubjectDataRegistration(id: string): SubjectDataRegistration | undefined {
  return SUBJECT_DATA_CATALOGUE_BY_ID.get(id);
}

export function assertSubjectDataRegistration(value: unknown): SubjectDataRegistration {
  return subjectDataRegistrationSchema.parse(value);
}

/** IDs with a code path in the current release. Other collector registrations
 * remain visible but block readiness until their source plan is enabled. */
export const AVAILABLE_SUBJECT_COLLECTORS = new Set([
  "openmapx-account",
  "openmapx-authentication",
  "openmapx-content",
  "openmapx-vehicles",
  "openmapx-sharing",
  "openmapx-timeline",
  "openmapx-mangrove",
  "openmapx-administration",
  "openmapx-offline",
  "openmapx-privacy-case",
  "openmapx-disclosures",
  "managed-dawarich-v1",
]);

export function catalogueAvailability(
  registration: SubjectDataRegistration,
): "available" | "unavailable" | "operator_review" | "not_applicable" {
  if (registration.strategy === "not_personal") return "not_applicable";
  if (registration.strategy === "operator_task") return "operator_review";
  return registration.collectorId && AVAILABLE_SUBJECT_COLLECTORS.has(registration.collectorId)
    ? "available"
    : "unavailable";
}
