"use client";

// Populate the runtime-singleton registry that community integration bundles
// resolve through the page's import map (apps/web/src/app/layout.tsx →
// /runtime/*.js, generated by scripts/build-runtime-modules.mjs). Each
// /runtime/*.js re-exports from `globalThis.__OMX_RUNTIME__[specifier]`, so a
// community bundle's `import "react"` / `@openmapx/*` resolve to the HOST's live
// instances — one React, one IntegrationRegistryContext — instead of bundling
// separate copies (which would break hooks and context across the boundary).
//
// This module assigns the global as an import side effect, so it must be
// imported before any community `<script type="module">` is appended
// (IntegrationProvider does that in an effect, after this runs at app start).

import * as Core from "@openmapx/core";
import * as IntegrationFramework from "@openmapx/integration-framework";
import * as IntegrationFrameworkReact from "@openmapx/integration-framework/react";
import * as Maplibre from "maplibre-gl";
import * as React from "react";
import * as JsxDevRuntime from "react/jsx-dev-runtime";
import * as JsxRuntime from "react/jsx-runtime";

declare global {
  // eslint-disable-next-line no-var
  var __OMX_RUNTIME__: Record<string, unknown> | undefined;
}

if (typeof globalThis !== "undefined") {
  globalThis.__OMX_RUNTIME__ = {
    react: React,
    "react/jsx-runtime": JsxRuntime,
    "react/jsx-dev-runtime": JsxDevRuntime,
    "@openmapx/core": Core,
    "@openmapx/integration-framework": IntegrationFramework,
    "@openmapx/integration-framework/react": IntegrationFrameworkReact,
    "maplibre-gl": Maplibre,
  };
}
